### ISSUE TITLE
Fix sync with AdventureBackpacks backpacks

### ISSUE THREAD

**Issue by Eufranio** [densitycraft/ForgePacketFix#3]
The backpacks doesn't appear when connecting trough the lobby.

https://github.com/runescapejon/AdventureBackpack2

**Comment by thomas15v** [comment]
This fix only works for thaumcraft atm. I am working on a global fix atm :smile:.

**Comment by thomas15v** [comment]
@Eufranio I applied the patch to this bungeecord: https://github.com/densitycraft/BungeeCord/releases. 
However keep in mine that bungeetablistplus and some other plugins might crash the client during server switch. 

In order to fix the id desync I send a packet that orders the client to throw away it's entire client game and rebuild it. This makes the client very unstable and sending the wrong packets to it in this stage can result in to a crash.
