### ISSUE TITLE
Player can't add elements to researching.

### ISSUE THREAD

**Issue by ccxufo** [densitycraft/ForgePacketFix#5]
I found a problem,when players research in Research Aspects. They couldn't  put the elements in Research Notes. 
I have test the forgePacketFix1.0 AND 1.0.1.

**Comment by thomas15v** [comment]
Hmm this "fix" is just still here so mod owners are aware that player id's are sometimes not unique across servers. I am not updating this fix anymore because it is simpler to just send the new id to the player.

This version of bungeecord will fix your issue: https://github.com/densitycraft/BungeeCord

**Comment by ccxufo** [comment]
Thanks a lot!
